aux_loss:
  use_aux_loss: true
  use_final_matches: false
  aux_loss_weight: 1.0
  transformer_decoder_layers: ${model.transformer.decoder.n_layers}

matcher:
  cost_coef_class: 10.0
  cost_coef_mask: 3.0
  cost_coef_dice: 5.0
  cost_coef_dist: 10.0
  cost_coef_nll: 0.0
  cost_coef_likelihood: 0.0
  cost_coef_box_l1: 1.0
  cost_coef_box_giou: 1.0

loss_weights:
  classification: 10.0
  mask_bce: 3.0
  mask_dice: 5.0
  distance_nll: 0.1
  distance_likelihood: 10.0
  distance_huber: 1.0
  salience: 1.0
  box_l1: 1.0
  box_giou: 1.0

no_electron_weight: 0.1
standardize_no_electron_weight: true

detach_likelihood_mean: false
huber_delta: 1.0

predict_box: ${model.predict_box}

use_denoising_loss: ${model.denoising.use_denoising}
denoising_loss_weight: ${model.denoising.denoising_loss_weight}

salience:
  alpha: 0.25
  gamma: 2.0

detection_metric_distance_thresholds: [0.05, 0.1, 0.5, 1.0, 5.0]
detection_metric_interval: ${training.print_interval}